### PR TITLE
Revert "build(deps): bump node-fetch from 2.6.7 to 3.3.2 (#359)"

### PR DESCRIPTION
**Pull request by austinvazquez**
*Issue #, if available:*
N/A

*Description of changes:*
This reverts commit da35ca94230a63bc9c17a8e453a90814540248bc.

The node-fetch dependency update is causing some issues in the backend AWS CodePipeline for Finch infrastructure. Revert the dependency update to unblock pipeline and have follow-up action items for addressing gaps between dependency update workflows and backend pipeline.

*Testing done:*

- [x] I've reviewed the guidance in CONTRIBUTING.md

#### License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by weikequ** [comment]
So the blocked pipeline isn't necessarily that big of a deal as our infra is already deployed. Do you think this would be a big undertaking to investigate+fix root cause?

**Comment by austinvazquez** [comment]
> So the blocked pipeline isn't necessarily that big of a deal as our infra is already deployed. Do you think this would be a big undertaking to investigate+fix root cause?

It is a fair question. I am a little biased because I pushed the update through and don't want to be the one blocking the pipeline. 😅 

It is a little difficult to gauge; I am still coming up to speed on this system and not very familiar with with Node development. What are your thoughts towards effort here based on your experience with the infrastructure?

**Comment by weikequ** [comment]
Could be related to this: https://github.com/node-fetch/node-fetch/issues/1657

**Comment by austinvazquez** [comment]
> Could be related to this: [node-fetch/node-fetch#1657](https://github.com/node-fetch/node-fetch/issues/1657). I don't think this issue has anything to do with the actual CDK code itself, just some dependencies/type related issue.

Agreed. Issue appears to be with upstream package. I have also expanded the GitHub Actions CI workflow to run `npm run build` so we only get updates which build.

**Review by pendo324 — APPROVED** [review]

**Review by weikequ — APPROVED** [review]

**Pull request merged**
